### ISSUE TITLE
Weird Errors booting Grapejuice

### ISSUE THREAD

**Issue by xendyex** [flathub/net.brinkervii.grapejuice#138]
### **I know, Byfron.**

Soooooo...
I'm getting errors starting Roblox App.
I lost one, but here they are:
This one was filled with [REDACTED] but I removed that. Here:

```
Traceback (most recent call last):
  File "/app/lib/python3/dist-packages/grapejuice/cli/cli_common.py", line 79, in wrapper
    return_value = fn(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3/dist-packages/grapejuice/cli/main.py", line 33, in player
    gtk_boot(player_main, gtk_main=False)
  File "/app/lib/python3/dist-packages/grapejuice_common/gtk/gtk_util.py", line 25, in gtk_boot
    main_function(*args, **kwargs)
  File "/app/lib/python3/dist-packages/grapejuice/cli/main.py", line 27, in player_main
    abstract_grapejuice().play_game(
  File "/app/lib/python3/dist-packages/grapejuice_common/abstraction/abstract_grapejuice_impl.py", line 58, in play_game
    _with_prefix_id(prefix_id, lambda prefix: prefix.roblox.run_roblox_player(uri))
  File "/app/lib/python3/dist-packages/grapejuice_common/abstraction/abstract_grapejuice_impl.py", line 45, in _with_prefix_id
    cb_wrapper(prefix)
  File "/app/lib/python3/dist-packages/grapejuice_common/abstraction/abstract_grapejuice_impl.py", line 41, in cb_wrapper
    _update_edge_update_state(pfx)
  File "/app/lib/python3/dist-packages/grapejuice_common/abstraction/abstract_grapejuice_impl.py", line 26, in _update_edge_update_state
    recipe.make_in(prefix)
  File "/app/lib/python3/dist-packages/grapejuice_common/recipes/recipe.py", line 66, in make_in
    self._make_in(prefix)
  File "/app/lib/python3/dist-packages/grapejuice_common/recipes/delete_edge_update_service_recipe.py", line 48, in _make_in
    prefix.core_control.kill_wine_server()
  File "/app/lib/python3/dist-packages/grapejuice_common/wine/wineprefix_core_control.py", line 544, in kill_wine_server
    subprocess.check_call([str(self.wine_server()), "-k"], env=env)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/app/patched_wine/bin/wineserver', '-k']' returned non-zero exit status 1.

``` 
Believe these are grapejuice file errors... any help?

**Comment by hello10293** [comment]
Try updating wine????
