### ISSUE TITLE
ubuntu grapejuice roblox studio does't work

### ISSUE THREAD

**Issue by aleeh011** [flathub/net.brinkervii.grapejuice#157]
--i dont are american sorry by the english--
i am in ubuntu 20.04.6 LTS , roblox studio does't install automatically (the robloxstudiobetalauncher.exe is not in the spected 
directory) and do a error message saying in the prompt something like "Basically the .exe is not there" i put it manualy and this started , but do a trace back error after install (probaly cus i do something wrong or is just a a problematic bug), i tried to install the dependence "ms edge webview2 " by grape juice option, but them (the instaler) crashes and not install, i aparently using opengl 4.6 (version 4.6.0 NVIDIA 470.223.02) and the 7.20.12 grapejuice version (i tried reinstall grapejuice and this dont work ) but the ms edge webview2 say wen i tried to install them the same message like this (a error ocurred in you istalation cus i dont like u) and closes

obs; the roblox run nomaly (and with a very good perfomance ). the studio is the issue (probaly becuse the ms edge webview2 dont install or i am a brainles person wohs cant make this run fine)

**Comment by aleeh011** [comment]
i forgot this (is what rapens whens i reinstall the grapejuice and try run studio) (the isntall roblox option dont make diference)

Traceback (most recent call last):
  File "/app/lib/python3/dist-packages/grapejuice/background.py", line 82, in run
    self.work()
  File "/app/lib/python3/dist-packages/grapejuice/tasks.py", line 32, in work
    abstract_grapejuice().launch_studio(self._prefix.configuration.id)
  File "/app/lib/python3/dist-packages/grapejuice_common/abstraction/abstract_grapejuice_impl.py", line 55, in launch_studio
    _with_prefix_id(prefix_id, lambda prefix: prefix.roblox.run_roblox_studio(ide=True))
  File "/app/lib/python3/dist-packages/grapejuice_common/abstraction/abstract_grapejuice_impl.py", line 48, in _with_prefix_id
    prefix.roblox.install_roblox(post_install_function=lambda: cb_wrapper(prefix))
  File "/app/lib/python3/dist-packages/grapejuice_common/wine/wineprefix_roblox.py", line 67, in install_roblox
    self._core_control.run_exe(
  File "/app/lib/python3/dist-packages/grapejuice_common/wine/wineprefix_core_control.py", line 511, in run_exe
    return do_run_exe(
           ^^^^^^^^^^^
  File "/app/lib/python3/dist-packages/grapejuice_common/logs/log_util.py", line 13, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3/dist-packages/grapejuice_common/wine/wineprefix_core_control.py", line 170, in do_run_exe
    post_run_function()
  File "/app/lib/python3/dist-packages/grapejuice_common/abstraction/abstract_grapejuice_impl.py", line 48, in <lambda>
    prefix.roblox.install_roblox(post_install_function=lambda: cb_wrapper(prefix))
                                                               ^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3/dist-packages/grapejuice_common/abstraction/abstract_grapejuice_impl.py", line 42, in cb_wrapper
    cb(pfx)
  File "/app/lib/python3/dist-packages/grapejuice_common/abstraction/abstract_grapejuice_impl.py", line 55, in <lambda>
    _with_prefix_id(prefix_id, lambda prefix: prefix.roblox.run_roblox_studio(ide=True))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3/dist-packages/grapejuice_common/wine/wineprefix_roblox.py", line 250, in run_roblox_studio
    launcher_path = self.roblox_studio_launcher_path
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3/dist-packages/grapejuice_common/wine/wineprefix_roblox.py", line 120, in roblox_studio_launcher_path
    return self.locate_roblox_executable("RobloxStudioLauncherBeta.exe")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3/dist-packages/grapejuice_common/wine/wineprefix_roblox.py", line 114, in locate_roblox_executable
    raise RobloxExecutableNotFound(executable_name)
grapejuice_common.errors.RobloxExecutableNotFound: Roblox executable 'RobloxStudioLauncherBeta.exe' could not be found!

**Comment by hello10293** [comment]
Did you try specifying the path to Roblox Studio in the settings?

**Comment by aleeh011** [comment]
yes, in the 3 options, i enabled the studio option and stay this problem (i reinstaled grapejuice too), seems like the folder of roblox studio doen`st exist in the c disk wen  i open it and see its inside, thers only one version in the roblox folder (roblox player). idk much but i supose its suposed to have a studio laucnher in some local of c disk, i put them here and then crashes when open via grapejuice open studio option

**Comment by aleeh011** [comment]
![Captura de tela de 2023-12-02 09-39-41](https://github.com/flathub/net.brinkervii.grapejuice/assets/151472950/e6385cc7-58ea-4f7b-9b57-b76fe86f354f)
![Captura de tela de 2023-12-02 09-46-59](https://github.com/flathub/net.brinkervii.grapejuice/assets/151472950/93c27539-392c-40dc-8062-d493680c2c20)



i am from brazil becuse it is in portuguese-brazil

**Comment by aleeh011** [comment]
my gt 1030 is the problem i buy a ney gpu

**Comment by bruno12fb** [comment]
same ocurred to me, how u fixed it?
