### ISSUE TITLE
When trying to open fflags it doesnt get past extraction.

### ISSUE THREAD

**Issue by Mrmidget23** [flathub/net.brinkervii.grapejuice#37]
When I try to extract I get this error
Traceback (most recent call last):
  File "/app/lib/python3.10/pip_deps/grapejuice/background.py", line 82, in run
    self.work()
  File "/app/lib/python3.10/pip_deps/grapejuice/tasks.py", line 57, in work
    abstract_grapejuice().extract_fast_flags()
  File "/app/lib/python3.10/pip_deps/grapejuice_common/abstraction/abstract_grapejuice_impl.py", line 57, in extract_fast_flags
    recipe.make_in(prefix)
  File "/app/lib/python3.10/pip_deps/grapejuice_common/recipes/recipe.py", line 54, in make_in
    self._make_in(prefix)
  File "/app/lib/python3.10/pip_deps/grapejuice_common/recipes/roblox_studio_recipe.py", line 25, in _make_in
    prefix.roblox.run_roblox_studio()
  File "/app/lib/python3.10/pip_deps/grapejuice_common/wine/wineprefix_roblox.py", line 225, in run_roblox_studio
    launcher_path = self.roblox_studio_launcher_path
  File "/app/lib/python3.10/pip_deps/grapejuice_common/wine/wineprefix_roblox.py", line 113, in roblox_studio_launcher_path
    return self.locate_roblox_executable("RobloxStudioLauncherBeta.exe")
  File "/app/lib/python3.10/pip_deps/grapejuice_common/wine/wineprefix_roblox.py", line 107, in locate_roblox_executable
    raise RobloxExecutableNotFound(executable_name)
grapejuice_common.errors.RobloxExecutableNotFound: Roblox executable 'RobloxStudioLauncherBeta.exe' could not be found!

**Comment by lunarlattice0** [comment]
You need to install Roblox Studio before extracting fflags.

**Comment by lunarlattice0** [comment]
Closed due to inactivity.
